// Code generated by protoc-gen-go.
// source: userland.proto
// DO NOT EDIT!

/*
Package userland is a generated protocol buffer package.

It is generated from these files:
	userland.proto

It has these top-level messages:
	Users
	User
*/
package userland

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Users struct {
	User             []*User `protobuf:"bytes,1,rep,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}

func (m *Users) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Login            *string `protobuf:"bytes,2,req,name=login" json:"login,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	CreatedAt        *int32  `protobuf:"varint,4,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt        *int32  `protobuf:"varint,5,opt,name=updated_at" json:"updated_at,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *User) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() int32 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int32 {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return 0
}

func init() {
}
