### Generated by rprotoc. DO NOT EDIT!
### <proto file: userland.proto>
# package userland;
# message Users {
#   repeated User user = 1;
# }
# 
# message User {
#   required int32 id = 1;
#   required string login = 2;
#   optional string password = 3;
#   optional int32 created_at = 4;
#   optional int32 updated_at = 5;
# }
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Userland
  class Users < ::Protobuf::Message
    defined_in __FILE__
    repeated :User, :user, 1
  end
  class User < ::Protobuf::Message
    defined_in __FILE__
    required :int32, :id, 1
    required :string, :login, 2
    optional :string, :password, 3
    optional :int32, :created_at, 4
    optional :int32, :updated_at, 5
  end
end